/**
 * Dynamic app content for auth and dashboard pages.
 * Served via automation.getAppContent so login, register, forgot-password, and dashboard are fully dynamic.
 */

export const appContent = {
  login: {
    title: "تسجيل الدخول",
    subtitle: "أدخل بياناتك للوصول إلى حسابك",
    tabEmail: "بريد",
    tabPhone: "هاتف",
    labelEmail: "البريد الإلكتروني",
    labelPassword: "كلمة المرور",
    placeholderEmail: "example@email.com",
    placeholderPassword: "••••••••",
    rememberMe: "تذكرني",
    forgotPasswordLink: "نسيت كلمة المرور؟",
    labelPhone: "رقم الهاتف",
    placeholderPhone: "+216 XX XXX XXX",
    otpHint: "سنرسل لك رمز تحقق (OTP) عبر الرسائل القصيرة",
    changeNumber: "تغيير الرقم",
    labelOtp: "رمز التحقق (OTP)",
    submitLogin: "تسجيل الدخول",
    sendOtp: "إرسال الرمز",
    sendingOtp: "جاري الإرسال…",
    noAccount: "ليس لديك حساب؟",
    registerLink: "سجل الآن",
    welcomeTitle: "مرحباً بك مرة أخرى",
    welcomeSubtitle:
      "سجل الدخول للوصول إلى لوحة التحكم الخاصة بك وإدارة تقاريرك ونقاطك",
    bullets: [
      "إدارة التقارير بسهولة",
      "تتبع النقاط والإحالات",
      "وصول آمن ومحمي",
    ],
  },
  register: {
    stepTitles: ["معلوماتك الشخصية", "معلومات الشركة", "نوع المنتجات"],
    stepDescriptions: [
      "أدخل معلوماتك الشخصية للبدء",
      "أدخل معلومات شركتك",
      "اختر نوع المنتجات التي تبيعها",
    ],
    productOptions: [
      "إلكترونيات",
      "ملابس وأزياء",
      "أغذية ومشروبات",
      "أثاث ومنزل",
      "أدوات تجميل",
      "كتب ووسائل تعليمية",
      "ألعاب وترفيه",
      "رياضة ولياقة",
      "صحة وطب",
      "أخرى",
    ],
    labels: {
      fullName: "الاسم الكامل",
      email: "البريد الإلكتروني",
      phone: "رقم الهاتف",
      password: "كلمة المرور",
      confirmPassword: "تأكيد كلمة المرور",
      companyName: "اسم الشركة",
      companyAddress: "عنوان الشركة",
      companyPhone: "هاتف الشركة",
      companyEmail: "بريد الشركة الإلكتروني",
      productTypes: "اختر نوع المنتجات التي تبيعها",
      placeholderName: "أدخل اسمك الكامل",
      placeholderCompany: "أدخل اسم الشركة",
      placeholderAddress: "أدخل عنوان الشركة",
      emailInvalid: "البريد الإلكتروني غير صحيح",
      phoneInvalid: "رقم الهاتف غير صحيح (يجب أن يكون رقم تونسي)",
      passwordsNoMatch: "كلمات المرور غير متطابقة",
      passwordStrength: "قوة كلمة المرور:",
      selectOneProduct: "يجب اختيار نوع واحد على الأقل",
      agreeTerms: "أوافق على",
      termsAndConditions: "الشروط والأحكام",
      privacyPolicy: "سياسة الخصوصية",
    },
    passwordStrengthLabels: ["ضعيف جداً", "ضعيف", "متوسط", "قوي", "قوي جداً"],
    buttons: {
      previous: "السابق",
      next: "التالي",
      submit: "إنشاء حساب",
    },
    haveAccount: "لديك حساب بالفعل؟",
    loginLink: "تسجيل الدخول",
    termsAlert: "يجب الموافقة على الشروط والأحكام",
  },
  forgotPassword: {
    title: "نسيت كلمة المرور؟",
    description:
      "أدخل بريدك الإلكتروني وسنرسل لك رابطاً لإعادة تعيين كلمة المرور",
    labelEmail: "البريد الإلكتروني",
    submitButton: "إرسال",
    sendingText: "جاري الإرسال...",
    backToLogin: "العودة لتسجيل الدخول",
    successMessage: "تم إرسال رابط إعادة تعيين كلمة المرور إلى بريدك",
    errorMessage: "يرجى إدخال البريد الإلكتروني",
  },
  dashboard: {
    brandName: "Tunisia Trust Engine",
    pageTitle: "لوحة تحكم مبسطة",
    pageSubtitle: "كل ما تحتاجه اليوم في مكان واحد.",
    merchantBadge: "حساب التاجر",
    loadingText: "جاري تحميل لوحة التحكم...",
    errorText: "تعذر تحميل البيانات. حاول مرة أخرى.",
    cards: {
      totalOrders: "إجمالي الطلبات",
      successRate: "نسبة النجاح",
      rto: "RTO",
      revenue: "الإيرادات",
      quickActions: "إجراءات سريعة",
      recentOrders: "آخر الطلبات",
      riskSummary: "ملخص المخاطر",
      noOrders: "لا توجد طلبات بعد.",
      lowRiskOrders: "طلبات منخفضة المخاطر",
      needsReview: "طلبات تحتاج مراجعة",
      tip: "نصيحة: فعّل قواعد \"السياسة التلقائية\" من صفحات MVP لتقليل الـ RTO.",
    },
    quickActions: [
      { id: "phone-verification", label: "تحقق من رقم", path: "/phone-verification" },
      { id: "reports", label: "إضافة تقرير", path: "/reports" },
      { id: "plugins", label: "إدارة الإضافات", path: "/plugins" },
      { id: "innovation", label: "أفكار MVP", path: "/innovation-lab" },
    ],
    menuGroups: [
      {
        label: "الرئيسية",
        items: [
          { id: "dashboard", label: "لوحة التحكم / لوحة المستخدم", path: "/dashboard" },
        ],
      },
      {
        label: "الطلبات والتحقق",
        items: [
          { id: "orders", label: "الطلبات", path: "/orders" },
          { id: "phone-verification", label: "التحقق من الهاتف", path: "/phone-verification" },
        ],
      },
      {
        label: "التقارير والاعتمادات",
        items: [
          { id: "reports", label: "التقارير", path: "/reports" },
          { id: "credits", label: "الاعتمادات", path: "/credits" },
          { id: "referrals", label: "الإحالات", path: "/referrals" },
        ],
      },
      {
        label: "الإحصائيات والتحليلات",
        items: [
          { id: "analytics", label: "الإحصائيات", path: "/analytics" },
          { id: "innovation-lab", label: "مختبر الابتكار", path: "/innovation-lab" },
        ],
      },
      {
        label: "التكامل والإعدادات",
        items: [
          {
            id: "plugins",
            label: "الإضافات",
            path: "/plugins",
            subItems: [
              { label: "كل الإضافات", path: "/plugins" },
              { label: "حلول فيسبوك وإنستغرام", path: "/plugins/social-sellers" },
            ],
          },
          { id: "settings", label: "الإعدادات", path: "/settings" },
        ],
      },
      {
        label: "المساعدة والدعم",
        items: [
          {
            id: "support",
            label: "الدعم",
            path: "/support",
            subItems: [
              { label: "اتصل بنا", path: "/support/contact" },
              { label: "الإبلاغ عن مشكلة", path: "/support/report" },
            ],
          },
        ],
      },
    ],
  },
  orders: {
    pageTitle: "إدارة الطلبات",
    pageSubtitle: "عرض وإدارة جميع طلباتك",
    loadingText: "جاري التحميل...",
    errorText: "حدث خطأ في تحميل الطلبات",
    filterOrderStatus: "حالة الطلب",
    filterVerification: "حالة التحقق",
    resetFilters: "إعادة تعيين",
    tableTitle: "قائمة الطلبات",
    tableCount: "عرض {count} طلب",
    statusAll: "الكل",
    statusPlaced: "تم الطلب",
    statusShipped: "تم الشحن",
    statusDelivered: "تم التسليم",
    statusReturned: "مرتجع",
    statusCancelled: "ملغي",
    verificationAll: "الكل",
    verificationPending: "قيد الانتظار",
    verificationVerified: "تم التحقق",
    verificationFailed: "فشل",
    verificationRejected: "مرفوض",
    colPhone: "رقم الهاتف",
    colAmount: "المبلغ",
    colTrust: "درجة الثقة",
    colVerification: "التحقق",
    colStatus: "الحالة",
    colDate: "التاريخ",
    colActions: "الإجراءات",
    noOrders: "لا توجد طلبات",
  },
  settings: {
    pageTitle: "الإعدادات",
    pageSubtitle: "الملف الشخصي، مفتاح API، والإعدادات التلقائية",
    loadingText: "جاري التحميل...",
    profileTab: "الملف الشخصي",
    apiTab: "مفتاح API",
    automationTab: "الإعدادات التلقائية",
    saveProfile: "حفظ التغييرات",
    regenerateApiKey: "إعادة إنشاء المفتاح",
    labels: {
      businessName: "اسم النشاط",
      email: "البريد الإلكتروني",
      phone: "رقم الهاتف",
      city: "المدينة",
      address: "العنوان",
    },
    successUpdate: "تم تحديث الملف الشخصي بنجاح",
    errorUpdate: "فشل التحديث",
  },
  credits: {
    pageTitle: "الاعتمادات",
    pageSubtitle: "رصيدك واستهلاكك وكيفية كسب الاعتمادات",
    tabBalance: "الرصيد",
    tabHistory: "سجل الاعتمادات",
    tabEarn: "كيفية الكسب",
    lowBalanceTitle: "رصيدك منخفض",
    lowBalanceMessage: "لديك أقل من {threshold} اعتماد. فحص رقم واحد يستهلك {cost} اعتمادات.",
    buyCredits: "شراء اعتمادات",
    loadingText: "جاري التحميل...",
  },
  reports: {
    pageTitle: "التقارير",
    pageSubtitle: "إضافة وعرض تقارير الطلبات والعملاء",
    newReport: "تقرير جديد",
    listReports: "قائمة التقارير",
    loadingText: "جاري التحميل...",
    reportKindOptions: [
      { value: "rto", label: "مرتجع (RTO)" },
      { value: "fraud", label: "احتيال" },
      { value: "complaint", label: "شكوى" },
      { value: "delivery_issue", label: "مشكلة تسليم" },
      { value: "other", label: "أخرى" },
    ],
  },
  referrals: {
    pageTitle: "الإحالات",
    pageSubtitle: "ادعُ تجاراً آخرين واكسب اعتمادات",
    loadingText: "جاري التحميل...",
  },
  analytics: {
    pageTitle: "الإحصائيات",
    pageSubtitle: "مخططات واتجاهات أداء الطلبات والتحقق",
    loadingText: "جاري التحميل...",
  },
  phoneVerification: {
    pageTitle: "التحقق من الهاتف",
    pageSubtitle: "تحقق من رقم عميل واحصل على درجة الثقة",
    loadingText: "جاري التحميل...",
  },
  plugins: {
    pageTitle: "الإضافات",
    pageSubtitle: "تثبيت وإدارة الإضافات والتكاملات",
    loadingText: "جاري التحميل...",
  },
  support: {
    pageTitle: "الدعم",
    pageSubtitle: "اتصل بنا أو أبلغ عن مشكلة",
    loadingText: "جاري التحميل...",
  },
  subscription: {
    pageTitle: "الاشتراك",
    pageSubtitle: "إدارة خطتك واعتماداتك",
    loadingText: "جاري التحميل...",
  },
} as const;
